
export enum ENGINE_STAGE {
    WORKFLOW_RUNNING = 'WORKFLOW-RUNNING',
    WORKFLOW_COMPLETED = 'WORKFLOW-COMPLETED',
    NODE_EXECUTE_BEFORE = 'NODE-EXECUTE-BEFORE',
    NODE_EXECUTE_AFTER = 'NODE-EXECUTE-AFTER',
}