
export enum ENGINE_STAGE {
    ENGINE_INIT = 'ENGINE-INIT',
    WORKFLOW_RUNNING = 'WORKFLOW-RUNNING',
    WORKFLOW_COMPLETED = 'WORKFLOW-COMPLETED',
    NODE_EXECUTE_BEFORE = 'NODE-EXECUTE-BEFORE',
    NODE_EXECUTE_AFTER = 'NODE-EXECUTE-AFTER',
    FUNCTION_CALL_START = 'FUNCTION-CALL-START',
    FUNCTION_CALL_END = 'FUNCTION-CALL-END',
}