
export enum ENGINE_STAGE {
    ENGINE_INIT = 'ENGINE-INIT',
    WORKFLOW_RUNNING = 'WORKFLOW-RUNNING',
    WORKFLOW_COMPLETED = 'WORKFLOW-COMPLETED',
    NODE_EXECUTE_BEFORE = 'NODE-EXECUTE-BEFORE',
    NODE_EXECUTE_AFTER = 'NODE-EXECUTE-AFTER',
    TOOL_START = 'TOOL-START',
    TOOL_END = 'TOOL-END',
}